"""
Helpers to test runtimes.
"""
import os
import glob
import pickle
import numpy
from numpy.testing import assert_array_almost_equal


def search_converted_models(root=None):
    """
    Searches for all converted models generated by
    unit tests in folders tests and with function
    *dump_data_and_model*.
    """
    if root is None:
        root = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "tests"))
        root = os.path.normpath(root)
    if not os.path.exists(root):
        raise FileNotFoundError("Unable to find '{0}'.".format(root))
    
    founds = glob.iglob(f"{root}/**/*.model.onnx", recursive=True)
    keep = []
    for found in founds:
        onnx = found
        basename = onnx[:-len(".model.onnx")]
        data = basename + ".data.pkl"
        model = basename + ".model.pkl"
        expected = basename + ".expected.pkl"
        res = dict(onnx=onnx, data=data, model=model, expected=expected)
        ok = True
        for k, v in res.items():
            if not os.path.exists(v):
                ok = False
        if ok:
            keep.append(res)
    return keep
    

def load_data_and_model(items_as_dict):
    """
    Loads every file in a dictionary with extension pkl
    for pickle.
    """
    res = {}
    for k, v in items_as_dict.items():
        if os.path.splitext(v)[-1] == ".pkl":
            with open(v, "rb") as f:
                res[k] = pickle.load(f)
        else:
            res[k] = v
    return res


def compare(expected, output, **kwargs):
    """
    Compares expected values and output.
    Returns None if no error, an exception message otherwise.
    """
    if isinstance(expected, numpy.ndarray) and isinstance(output, numpy.ndarray):
        try:
            assert_array_almost_equal(expected, output, **kwargs)
        except Exception as e:
            return e
    else:
        return TypeError("Unexpected types {0} != {1}".format(type(expected), type(output)))
    return None
