name: Black Format Checker
on: [push, pull_request]
jobs:
  black-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@343b8137f4dd7d912662eae5021ad9a023cfc89c  # stable 24.1.1
        with:
          options: "--diff --check"
          src: "."
  ruff-format-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: chartboost/ruff-action@v1.0.0
