name: Build Any Wheel

on:
  push:
    branches:
      - main
      - 'releases/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_wheels:
    name: Build wheel
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2

      - uses: actions/setup-python@v6
        with:
          python-version: '3.13'

      - name: Install build and twine
        run: python -m pip install build twine

      - name: Build wheel
        run: python -m build .

      - name: Check wheel
        run: python -m twine check ./dist/onnxmltools*.whl

      - uses: actions/upload-artifact@v7
        with:
          name: onnxmltools-wheel
          path: ./dist/onnxmltools*.whl
